// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApi;

#nullable disable

namespace RestaurantApi.Migrations
{
    [DbContext(typeof(RestaurantListDbContext))]
    partial class RestaurantListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("RestaurantApi.Restaurants", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Details = "just testing the api db",
                            Image = "empty",
                            Location = "Mandeville",
                            RestaurantName = "Test"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Details = "Say my name, say my name",
                            Image = "Empty",
                            Location = "Kingston",
                            RestaurantName = "Test2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
